
#ifndef _TMR1_CONFIG_H_
#define _TMR1_CONFIG_H_

/*
1. TMR1_NORMAL_MODE
2. TMR1_PWM_PHASE_CORRECT_8BIT
3. TMR1_PWM_PHASE_CORRECT_9BIT
4. TMR1_PWM_PHASE_CORRECT_10BIT
5. TMR1_CTC_MODE_COMP
6. TMR1_FAST_PWM_8BIT
7. TMR1_FAST_PWM_9BIT
8. TMR1_FAST_PWM_10BIT
9. TMR1_PWM_PHASE_FREQ_CORRECT_ICR
10. TMR1_PWM_PHASE_FREQ_CORRECT_CMP
11. TMR1_PWM_PHASE_CORRECT_MODE_ICR
12. TMR1_PWM_PHASE_CORRECT_MODE_CMP
13. TMR1_CTC_MODE_ICR
14. TMR1_FAST_PWM_MODE_ICR
15. TMR1_FAST_PWM_MODE_CMP
*/
#define TMR1_FAST_PWM_MODE_ICR




#endif 